package com.codevictims.propertymanagement.tenancy.type;
public enum TenantType { ACTIVE, INACTIVE, PENDING, OPEN, CLOSED, RESIDENTIAL, COMMERCIAL, SCHEDULED, DEPOSITED, CLEARED, BOUNCED, CANCELLED, CARD, CASH, BANK_TRANSFER, CHEQUE }
