package com.codevictims.propertymanagement.billing.type;
public enum ChequeStatus { ACTIVE, INACTIVE, PENDING, OPEN, CLOSED, RESIDENTIAL, COMMERCIAL, SCHEDULED, DEPOSITED, CLEARED, BOUNCED, CANCELLED, CARD, CASH, BANK_TRANSFER, CHEQUE }
