package com.codevictims.propertymanagement.account.type;
public enum Role { ACTIVE, INACTIVE, PENDING, OPEN, CLOSED, RESIDENTIAL, COMMERCIAL, SCHEDULED, DEPOSITED, CLEARED, BOUNCED, CANCELLED, CARD, CASH, BANK_TRANSFER, CHEQUE }
